# Terraform Provider release workflow.
name: Release

on:
    branches: main

permissions:
    contents: write

jobs:
    goreleaser:
        runs-on: ubuntu-latest
        steps:
            - name: Echo
              run:
                  echo "hello World"
